version: 1
type: "multi-grpc"
ports: "5000"
parameter-server:
  container: "1.1.0-cuda10.0-cudnn7.5-runtime "
  command: "pip install -r requirements.txt && python3 main.py  -a resnet18 /notebooks/storage/workspace/tiny-imagenet-200/"
  machine-type: "K80"
  count: 1
worker:
  container: "1.1.0-cuda10.0-cudnn7.5-runtime "
  command: "pip install -r requirements.txt && python3 main.py  -a resnet18 /notebooks/storage/workspace/tiny-imagenet-200/"
  machine-type: "K80"
  count: 2
# model:
#   type: Pytorch
#   path: '/artifacts'
# checks:
#   tensorflow:loss:
#     target: 0.0..1.0
#     aggregate: max
#   tensorflow:accuracy:
#     target: 0.988..1.000
#     aggregate: median
#   defaults:
#     precision: 3
